version: "3.3"
services:
  starlink_exporter:
    image: "sysdigdan/starlink_exporter:latest"
    restart: always
    ports:
      - "9817:9817"

  speedtest_exporter:
    image: "ghcr.io/danopstech/speedtest_exporter:latest"
    restart: always
    ports:
      - "9092:9090"

  blackbox:
    image: "ghcr.io/danopstech/blackbox_exporter:latest"
    restart: always
    user: "root"
    ports:
      - "9115:9115"
    volumes:
      - type: bind
        source: ./config/blackbox/config.yaml
        target: /etc/blackbox_exporter/config.yml

  prometheus:
    image: "ghcr.io/danopstech/prometheus:latest"
    restart: always
    user: "root"
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./config/prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: ./data/prometheus
        target: /prometheus

#  grafana:
#    image: "ghcr.io/danopstech/grafana:latest"
#    restart: always
#    user: "root"
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_INSTALL_PLUGINS=ae3e-plotly-panel
#      - GF_LOG_CONSOLE_LEVEL=warn
#    volumes:
#      - type: bind
#        source: ./data/grafana
#        target: /var/lib/grafana
#      - type: bind
#        source: ./config/grafana/provisioning
#        target: /etc/grafana/provisioning/

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
