global:
  scrape_interval:     1m
  evaluation_interval: 1m
  scrape_timeout:      10s

scrape_configs:
  - job_name: 'starlink'
    scrape_interval: 3s
    scrape_timeout:  3s
    static_configs:
      - targets: ['starlink_exporter:9817']

  - job_name: 'speedtest'
    scrape_interval: 60m
    scrape_timeout: 70s
    static_configs:
      - targets: [ 'speedtest_exporter:9090' ]

  - job_name: 'blackbox'
    scrape_interval: 3s
    scrape_timeout: 3s
    metrics_path: /probe
    params:
      module: [icmp_ipv4]
    static_configs:
      - targets: [ '8.8.8.8' ]
        labels:
          name: 'Google'
      - targets: [ '1.1.1.1' ]
        labels:
          name: 'Cloudflare'
      - targets: [ '4.2.2.2' ]
        labels:
          name: 'Level 3'
      - targets: [ 'ec2.us-east-1.amazonaws.com' ]
        labels:
          name: 'AWS East 1'
      - targets: [ 'ec2.us-west-2.amazonaws.com' ]
        labels:
          name: 'AWS West 2'
      - targets: [ 'core1.dal2.he.net' ]
        labels:
          name: 'HE Dallas'
      - targets: [ 'core2.tor1.he.net' ]
        labels:
          name: 'HE Toronto'
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
